### ISSUE TITLE
Garage state is not valid

### ISSUE THREAD

**Issue by DjAnu** [brchri/tesla-geogdo#10]
Hi, I have set up my Ratgdo with your app but I am getting following error everytime it fires an open/close command

![image](https://github.com/brchri/tesla-geogdo/assets/5419410/b18799a5-6114-4f54-9d95-a2b9487086d9)

FYI, I am using topic prefix as "ratgdo/" which is how it is set in my Ratgdo config page. Any idea what may be causing this error. I am using dry contact FW version and I was able to connect Ratgdo to habitat where I do get status as below 
 
![image](https://github.com/brchri/tesla-geogdo/assets/5419410/c9fcb156-3779-4921-aa1e-375a545d5908)

**Comment by brchri** [comment]
Take off the `/`, try with just `ratgdo` for your prefix; geogdo automatically adds the slash. If it still doesn't work, send me the `opener` section of your config (with anything sensitive scrubbed), and also connect to your MQTT broker with a tool like [MQTT Explorer](https://mqtt-explorer.com/) and send me a screenshot of the status topic of ratgdo. It looks like we just need to correct the topic it's subscribing to.

You can also enable debug logging by adding the `DEBUG=true` environment variable to your docker container. Then you should see it print a line like this when it starts up:

`[DEBUG  ] Subscribing to topic: ratgdo/status/availability`

and you'll want to make sure that matches up with what you see in MQTT Explorer for the availability topic.

**Comment by DjAnu** [comment]
Thanks lemme try that. Is it possible to test it somehow with out moving
the car in and out 😐?

**Comment by brchri** [comment]
Yep, just use MQTT Explorer to change the latitude or longitude value to something different, like add a whole number, that would simulate leaving. Then change it back to the original value to simulate returning home. So if the current lat is `123.4567`, just change it to `124.4567` and back again to simulate leaving and returning.

**Comment by DjAnu** [comment]
Here is the screenshot from container log
![image](https://github.com/brchri/tesla-geogdo/assets/5419410/ca998585-2f88-4ff4-9e89-9c5c6fe9383c)
And this is from MQTT explorer
ratgdo/Ratgdo-GDO/status/door

Seem like I need to add the ratgdo device name in config yml topic line...
I added that and now log seems to match the MQTT explorer status topic but I accidentally hit X on retained for latitude now I don't get Lat on teslamate :-(

**Comment by DjAnu** [comment]
Nevermind, I see Lat at the bottom now and Yes GDO is working now. Thanks a lot for your quick response. On a side note I see you have added an example for homebridge. Were you able to connect Ratgdo on Homebridge ? I am getting error on Homebridge plugin...

**Comment by brchri** [comment]
I don't use homebridge so no, I haven't gotten that working as I haven't tried, but I think users have been successfully using it. You might try the [plugin github page](https://github.com/hjdhjd/homebridge-ratgdo) or the [homebridge discord](https://discord.com/invite/homebridge-432663330281226270), I know the plugin developer is pretty active in there. Good luck with getting it working, and happy to hear geogdo is working!
